### ISSUE TITLE
Search Bug: Remove unnecessary fuzziness from search template

### ISSUE THREAD

**Issue by netmanito** [aemsites/volvotrucks-na#120]
### Issue Type

Bug

### Summary

Remove fuzziness from search template query

### Priority

High

### Description

Search query template has unnecessary `fuzzy` parameter in `multi_match` query, which makes return unwanted results.

**Technical Solution**
Remove
`\"fuzziness\": \"auto\" `
from `multi_match` query in eds_search_template

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

N/A

### Steps to Reproduce

N/A

### Expected Results

N/A

### Actual Results

N/A

**Comment by urtzi-sotes** [comment]
Changes deployed to production
