### ISSUE TITLE
Bug: [V2 Article Search] the search doesn't get appended correctly to pages

### ISSUE THREAD

**Issue by amglebihan** [aemsites/volvotrucks-na#122]
### Issue Type

Bug

### Priority

Blocker

### Description

While attempting to add the V2 Article Search block to the Magazine article template to meet this [requirement](https://github.com/aemsites/volvotrucks-na/issues/65), I noticed that the block fails to integrate correctly and does not appear on the page.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://main--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
2. Check the top of the page, above the Hero block, where the Search feature is expected to appear.

### Expected Results

The Search should appear above the Hero block.

### Actual Results

The Search is not appearing above the Hero block.

**Comment by jonatan-lledo-netcentric** [comment]
Tested by @silviulungu

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly.
