### ISSUE TITLE
Bug: [V2 Video (autoplay)] Block on Mobile Issue

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/volvotrucks-na#13]
### Issue Type

Bug

### Summary

The [V2 Video (autoplay, loop, disable-controls)] Block is not rendering as expected on mobile devices. 

### Description

The V2 Video Block configured with autoplay, loop, and disabled controls is not functioning as expected on mobile devices. Specifically, the video does not autoplay. Instead, the user first sees a low-res static image and when clicked, it opens in a modal screen rather than playing inline as it does on desktop.

### Affected Device Classes

Mobile

### Affected Browsers/Devices and Versions

Tested on iphone in Safari.

### Steps to Reproduce

1. Using a mobile device, navigate to volvotrucks.us
2. Scroll down on the home page to the electromobility video that's under the find a dealer section. 
3. Observe how there's a static image instead of auto-play video. 
4. Now click on the video, observe how it opens in a modal. 

### Expected Results

Video should automatically play when the user scrolls down to it, matching the same kind of experience seen in the hero and on the desktop user experience. 

### Actual Results

Autoplay is not working. 

### Attachment
![IMG_3337](https://github.com/user-attachments/assets/b8ef3429-72d8-4b53-bf77-fdf829021c5e)
![IMG_3338](https://github.com/user-attachments/assets/19e9161b-a60f-4f72-88a0-6d7dc676e2d5)
![IMG_3339](https://github.com/user-attachments/assets/ddaad1da-72c8-4953-8451-0a4db3c0c3f9)

**Comment by alexiscoelho** [comment]
"Expected Results
Video should automatically play when the user scrolls down to it, matching the same kind of experience seen in the hero and on the desktop user experience."

This is not a feature we have implemented. Can this be converted to a Change request please?
@ZoeBeykirch

**Comment by alexiscoelho** [comment]
Also, not sure if this will be possible due to iOS limitations in autoplay videos... will require some effort for sure
