### ISSUE TITLE
Bug: Youtube Video added on a Hero Block is not playing

### ISSUE THREAD

**Issue by Kannan-CM** [aemsites/volvotrucks-na#143]
### Issue Type

Bug

### Summary

Hero

### Priority

High

### Description

YouTube Video added to Hero block is not playing the Video.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Chrome, Safari, Edge

### Steps to Reproduce

1. Navigate to https://www.volvotrucks.us/trucks/powertrain/d13tc/
2. When the page loads click on "Play Video" button on the Hero image
3. Modal window with a message "No compatible source was found for this media." show up

### Expected Results

Video should be played on the Modal

### Actual Results

<img width="682" alt="image" src="https://github.com/user-attachments/assets/cd615b7d-c9dd-4af2-9278-45e6e44f552b">

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly.
