### ISSUE TITLE
Defect: New Infra: Volvotrucks.MX site consolidated issues 

### ISSUE THREAD

**Issue by silviulungu** [aemsites/volvotrucks-na#34]
**Volvotrucks.mx website consolidated issues**

**Out of Scope Code issues:**

- [ ] Code issues picked up in  aemsites/volvotrucks-na#22

Content Issues
- [ ] Parts and Services button is written in english instead of spanish and has no functionality. https://www.volvotrucks.mx/
- [ ] The button "Falleto del motor D13" which translates to "D13 Engine Failure" redirects the user to dealer locator, this is the right behavior? [volvotrucks.mx/powertrain/d13/](http://volvotrucks.mx/powertrain/d13/)

**Content issues:**

- [x] Missing content. https://www.volvotrucks.mx/news-and-stories/press-releases/
- [x] Articles images are missing on this page. https://www.volvotrucks.mx/news-and-stories/
- [x] Missing content. https://www.volvotrucks.mx/news-and-stories/volvo-trucks-magazine/under-one-roof/
- [x] Missing content. https://www.volvotrucks.mx/news-and-stories/volvo-trucks-magazine/fully-charged/
- [x] Missing content. https://www.volvotrucks.mx/news-and-stories/volvo-trucks-magazine/growing-footprint/
- [x] Missing content. https://www.volvotrucks.mx/news-and-stories/volvo-trucks-magazine/
- [ ] #117
- [ ] Missing content. https://www.volvotrucks.mx/our-difference/
- [x] Missing content. https://www.volvotrucks.mx/parts-and-services/training/
- [x] I can't access this page, please verify if you can. http://cvolvotrucks.mx/parts-and-services/services/service-and-maintenance-intervals/
- [ ] Missing content. https://www.volvotrucks.mx/parts-and-services/services/body-builder-support/request-for-assistance/
- [ ] Missing content. https://www.volvotrucks.mx/trucks/powertrain/i-shift-transmission/
- [ ] Missing content. https://www.volvotrucks.mx/trucks/emissions/
- [ ] Missing content. https://www.volvotrucks.mx/parts-and-services/services/body-builder-support/faqs/
- [x] Error 404. https://www.volvotrucks.mx/media/vtna/files/shared/body-builder/manuals/2023/volvo-bbm-updates-1-27-2023.pdf
- [x] Error 404. https://www.volvotrucks.mx/media/vtna/files/shared/body-builder/manuals/volvo-section-0-body-builder-general-information.pdf
- [x] Error 404. https://www.volvotrucks.mx/media/vtna/files/shared/body-builder/manuals/2022/volvosection1oil-filter.pdf
- [x] Error 404. https://www.volvotrucks.mx/media/vtna/files/shared/body-builder/manuals/2023/maint-1567837-volvo-section-3-vecu4-updates.pdf
- [x] Error 404. https://www.volvotrucks.mx/media/vtna/files/shared/body-builder/manuals/2023/volvo-section-4-update-002.pdf
- [x] Error 404. https://www.volvotrucks.mx/media/vtna/files/shared/body-builder/manuals/2022/volvo-section-6-axle-and-suspension.pdf

**Comment by Varunvolvo** [comment]
Hi @williebender,  Based on the details that I shared you yesterday
do we have any update or any lead to whom we can reach out to...

**Comment by Varunvolvo** [comment]
All the checked box items are completed. The unchecked box items can be ignored, since those pages are not required for MX site.
