### ISSUE TITLE
Defect: New Infra: Volvotrucks.CA site consolidated issues

### ISSUE THREAD

**Issue by girishdigrajkar** [aemsites/volvotrucks-na#36]
Volvotrucks.ca website consolidated issues

Current Code Issues: 
- [x] Cookie integration done ? Unable to see any cookie acceptance popup

**Content issues:**

1. [x] Homepage >> Electromobility section does not play video (V2 Video) instead shows URL : https://www.volvotrucks.ca/en-ca/all-new-vnl/Videos/media_1aadb6f055d9e6ebd5222d7752abc5a1598c55a2f.mp4
2. [x]   Homepage >> ‘Our truck lineup’ section >> VNL >> Click on Build yours >> Displays error page
3. [x] Homepage >> ‘Our truck lineup’ section >> VNR >> Click on Build yours >> Displays error page
4. [x] Homepage >> Find a Dealer >> Search for Ontario >> on dealer list observe >> Unable to click on ‘Dealer website ‘ seems data not setup e.g.Integrity Ventures Inc.
5. [x] Homepage >> v2-stories-carousel block >> First and last image has unexpected white dot icons & Button is not having link text instead it is outside button area Also, the Navigation arrows are not displayed
6. [x] Header >> Services >> Genuine / Go to https://www.volvotrucks.ca/en-ca/parts-and-services/parts/genuine/ >> Transmission card > click on [Learn More](https://www.volvotrucks.ca/en-ca/parts-and-services/parts/genuine/transmission/) >> Page is not displayed
7. [x] Header >> Services >> Genuine/ Go to https://www.volvotrucks.ca/en-ca/parts-and-services/parts/genuine/ >> Cab, Body, and Accessories card > click on [Learn More](https://www.volvotrucks.ca/en-ca/parts-and-services/parts/genuine/cab-body-accessories/) >> Page is not displayed
8. [x] Header >> Services >> [Volvo Reman](https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/) / Go to https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/ >> Hero image >> Click on [View Brochure](https://www.volvotrucks.ca/en-ca/media/vtna/files/shared/body-builder/manuals/2023/vpm-23-007-volvo-reman-brochure051223.pdf) >> 404 page
9. [x] Header >> Services >> [Volvo Reman](https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/) / Go to https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/ >>Transmission card >> click on [Learn More](https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/transmission/) >> Page is not displayed
10. [x] Header >> Services >> [Volvo Reman](https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/) / Go to https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/ >>Overhaul Program card >> click on [Learn More](https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/overhaul-program/) >> Page is not displayed
11. [x] Header >> Services >> All Makes  >>   displays no page
12. [x] https://www.volvotrucks.ca/en-ca/trucks/vnr-electric/ >> Explore financing link shows page is not displayed
13. [x] https://www.volvotrucks.ca/en-ca/trucks/all-new-vnl/#interior >> Click on + [EXPLORE LIVING ENVIRONMENT](https://www.volvotrucks.ca/en-ca/trucks/all-new-vnl/living-environment) >> blank page is displayed
14. [x] https://www.volvotrucks.ca/en-ca/trucks/all-new-vnl/#safety >> Click on + [EXPLORE SAFETY](https://www.volvotrucks.ca/en-ca/trucks/all-new-vnl/safety) >> blank page is displayed
15. [x] https://www.volvotrucks.ca/en-ca/trucks/vhd/ >>. Find a dealer link has white back colour which is not a good user experience
16. [x] Footer link >> [Act Against Forced Labor Policy](https://www.volvotrucks.ca/en-ca/media/vtna/files/2024-05-15-vgci-report.pdf) is spanning two rows instead it could be in single line for desktop view as it looks odd
17. [x] https://www.volvotrucks.ca/en-ca/trucks/powertrain/d13tc/  : Videos does not play
18. [x] https://www.volvotrucks.ca/en-ca/trucks/powertrain/cummins-x15/   & https://www.volvotrucks.ca/en-ca/trucks/powertrain/natural-gas/    & https://www.volvotrucks.ca/en-ca/trucks/emissions/       : Page not found
19. [x]  https://www.volvotrucks.ca/en-ca/parts-and-services/parts/remanufactured/engine/. >> View PDF >>. 404 error page
20. [x] https://www.volvotrucks.ca/en-ca/parts-and-services/services/service-and-maintenance-intervals/ >> PDF link results in 404 page &  Image is not displayed
21. [x] Header >> click About us link  >>. Click on Careers (https://www.volvotrucks.ca/en-ca/links/megamenu/careers/). shows page cannot be displayed 

Out of Scope Code Changes 
**Code issues :** 

1. [x] Search is not enabled - This is intentional. 
2. [x] Footer >> When clicked on [Safety recalls](https://www.volvotrucks.us/recalls/) it shows page in new browser tab unlike us in same tab - This is intentional.

**Comment by Varunvolvo** [comment]
Unchecked points - need support from dev team in fixing it.
