### ISSUE TITLE
FR: Change "Arial" Fallback Font CSS to "NotoSans"

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/volvotrucks-na#56]
### Description

To comply with legal requirements, the fallback font "Arial," owned by Monotype, must be replaced. "Noto Sans," an open-source font, will serve as the new CSS fallback font on the Volvo website domains.

### Acceptance Criteria 
- [x]  Remove all fallback font information related to “Arial” and change it to [“NotoSans” ](https://fonts.google.com/noto/specimen/Noto+Sans) for all North American Volvo Trucks domains:
   - [x]  [Volvo Trucks USA](https://www.volvotrucks.us/)
   - [x] [Volvo Trucks Canada English](https://www.volvotrucks.ca/en-ca/)
   - [x] [Volvo Trucks Canada French](https://www.volvotrucks.ca/fr-ca/)
   - [x] [Volvo Trucks Mexico ](https://www.volvotrucks.us/)

### Related Tickets
https://github.com/hlxsites/vg-roadchoice-com/issues/251
https://github.com/hlxsites/vg-partsasist/issues/114
https://github.com/hlxsites/vg-macktrucks-com/issues/788

**Comment by girishdigrajkar** [comment]
Below observations are noted:

1. 'Feedback' has Arial font :
https://files.slack.com/files-pri/T04650MFY-F084Q2W24S1/image.png

2. Find a dealer >>  google disclaimer on right hand lower corner of map >> 'Keyboard shortcuts'  ' Map Data 2024 Google .....' Terms etc.  is in Arial.
3. Contact us form ( Again 3rd party) has Arial font :
![image](https://github.com/user-attachments/assets/66ed08d0-7370-40bb-a02a-9f91eb8e2c66)
4. Open any page on website and you see Arial font being mentioned in style ( It could be seen in page source but no Arial font text on page) ... Please see below screenshot :
![image](https://github.com/user-attachments/assets/22ffbb41-eff9-428e-afb4-14346c7d8a37)
5. Website Images too could have Arial fonts present

**Comment by jonatan-lledo-netcentric** [comment]
4th item is injected by Hotjar, so a 3rd party script. IMHO no action is needed

**Comment by girishdigrajkar** [comment]
Thanks for confirmation @jonatan-lledo-netcentric, to summarise, Arial font is not used in code of EDS scope (except for 3rd party which Volvo is going to take up separately) hence, this ticket could be closed ...
