### ISSUE TITLE
Bug: Minor: Volvo Footer 'Do not sell or share my personal information' is misaligned

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/volvotrucks-na#72]
### Description
On the global footer for https://www.volvotrucks.us/ the item 'Do not sell or share my personal information' is misaligned, positioned slightly below the other items that display before it. This should be corrected so that it is exactly parallel with the rest of the footer. 

![Image](https://github.com/aemsites/volvotrucks-na/assets/125895595/2dfbaa07-714b-465b-b562-76b975db178e)

### Notes
This is currently working on production. However, it is not working on unpublished pages (more details and link needed).

**Comment by Meli-lazarte** [comment]
Closing the ticket since it is working in prod as expected.
